try:
    raise NameError('HiThere')

except NameError as NE:
    print('An exception flew by!')

